[package]
name = "nt-usb-plus-on-linux"
version = "0.1.0"
description = "Control panel for the RØDE NT-USB+ on Linux"
edition = "2021"
license = "MIT"
publish = false

[lib]
name = "nt_usb_plus_on_linux"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "0.2"
alsa = "0.12"
ureq = "3.4.2"

[profile.release]
lto = true
opt-level = "s"
strip = true
